name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shfmt
        run: sudo snap install shfmt
      - name: Run shfmt
        run: shfmt -d entrypoint.sh
